language: node_js

node_js:
    - "io.js"
    - "0.12"
    - '0.10'

before_install:
    - npm install -g grunt-cli

install:
    - npm install

before_script:
    - grunt test

notifications:
    email: false
